### PR TITLE
embed org.apache.maven.shared:maven-invoker lib into ch.vorburger.osgi.gradle bundle

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
hey @edewit when I was trying to set this up again (from scratch), I was struggling with the error shown below... this change fixes that, but I'm curious, how the new Maven support ever actually worked, for you without this?

`[15:55:45 ERROR] [ch.vorburger.minecraft.osgi.OSGiFrameworkWrapper]: Failed to start bundle ch.vorburger.osgi.gradle
org.osgi.framework.BundleException: Unable to resolve ch.vorburger.osgi.gradle [7](R 7.0): missing requirement [ch.vorburger.osgi.gradle [7](R 7.0)] osgi.wiring.package; (osgi.wiring.package=org.apache.maven.shared.invoker) Unresolved requirements: [[ch.vorburger.osgi.gradle [7](R 7.0)] osgi.wiring.package; (osgi.wiring.package=org.apache.maven.shared.invoker)]`

**Comment by edewit** [comment]
Could it be that I added this dependency: https://github.com/edewit/minecraft-plugin-centos/blob/s2i/server/osgi/boot/3_maven-invoker-4.0.0-SNAPSHOT.jar which has the osgi meta data already in it?

**Comment by vorburger** [comment]
@edewit yeah, that would explain it... you probably locally re-built that? Where's the source for it? :smile: To simplify deployment, how about we merge this change - +1? Then you don't need that 3_maven-invoker-4.0.0-SNAPSHOT.jar anymore.

**Comment by edewit** [comment]
no got it from maven central like that

**Comment by edewit** [comment]
can't merge this branch as I don't have write access

**Pull request merged**
